# Generated by Django 4.0.5 on 2022-09-14 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='enrolled_in_course',
            field=models.ManyToManyField(blank=True, default=None, related_name='courses', to='lessons.course'),
        ),
        migrations.AddField(
            model_name='learner',
            name='learner_on_waitlist',
            field=models.ManyToManyField(blank=True, default=None, related_name='waitlists', to='lessons.waitlist'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='associated_with_learner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.learner'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='course_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.course'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
