# Generated by Django 4.0.5 on 2022-09-20 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_learner_associated_with_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='associated_with_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
