# Generated by Django 4.0.5 on 2022-09-29 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_learner_associated_with_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='associated_with_learner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.learner'),
        ),
    ]
