# Generated by Django 4.0.5 on 2022-09-29 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_associated_with_learner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='associated_with_learner',
        ),
    ]
