# Generated by Django 4.0.5 on 2022-10-07 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_associated_with_learner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='enrolled_in_course',
        ),
        migrations.RemoveField(
            model_name='learner',
            name='learner_on_waitlist',
        ),
    ]
