# Generated by Django 4.0.5 on 2022-08-12 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_age_range', models.CharField(max_length=100)),
                ('course_location', models.CharField(max_length=100)),
                ('course_start_date', models.DateField()),
                ('course_end_date', models.DateField()),
                ('course_day_of_week', models.CharField(max_length=100)),
                ('course_time', models.TimeField()),
                ('spots_available', models.CharField(max_length=100)),
                ('num_spots_available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.course')),
            ],
        ),
    ]
