# Generated by Django 4.1.3 on 2022-12-09 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_title", models.CharField(default=None, max_length=100)),
                ("course_description", models.CharField(max_length=250)),
                ("course_age_range_min", models.CharField(max_length=50, null=True)),
                ("course_age_range_max", models.CharField(max_length=50, null=True)),
                ("course_location", models.CharField(max_length=100)),
                (
                    "course_start_date",
                    models.DateField(
                        help_text="Enter the date this course will begin.", null=True
                    ),
                ),
                (
                    "course_end_date",
                    models.DateField(
                        help_text="Enter the date this course will end.", null=True
                    ),
                ),
                (
                    "course_day_of_week",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "course_start_time",
                    models.TimeField(
                        help_text="Enter the start time for this course in Hawaii Standard Time (e.g., 01:00 PM).",
                        null=True,
                    ),
                ),
                (
                    "course_end_time",
                    models.TimeField(
                        help_text="Enter the end time for this course in Hawaii Standard Time(e.g., 02:00 PM).",
                        null=True,
                    ),
                ),
                ("num_spots_available", models.IntegerField(null=True)),
                (
                    "course_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Enter price in US dollars.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "course_instructor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "learner_on_roster",
                    models.ManyToManyField(
                        related_name="learners", to="accounts.learner"
                    ),
                ),
                (
                    "learner_on_waitlist",
                    models.ManyToManyField(
                        related_name="waitlisted", to="accounts.learner"
                    ),
                ),
            ],
        ),
    ]
