# Generated by Django 4.0.5 on 2022-09-14 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(default=None, max_length=100)),
                ('course_description', models.CharField(max_length=250)),
                ('course_age_range_min', models.IntegerField(null=True)),
                ('course_age_range_max', models.IntegerField(null=True)),
                ('course_location', models.CharField(max_length=100)),
                ('course_start_date', models.DateField(help_text='Enter the date this course will begin.')),
                ('course_end_date', models.DateField(help_text='Enter the date this course will end.')),
                ('course_day_of_week', models.CharField(max_length=100)),
                ('course_start_time', models.TimeField(help_text='Enter the start time for this course (e.g., 01:00 PM)')),
                ('course_end_time', models.TimeField(help_text='Enter the end time for this course (e.g., 02:00 PM)')),
                ('num_spots_available', models.IntegerField()),
                ('course_instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('learner_on_roster', models.ManyToManyField(blank=True, default=1, related_name='learners', to='accounts.learner')),
            ],
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.course')),
                ('course_instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listed_on_waitlist', models.ManyToManyField(blank=True, related_name='waitlists', to='accounts.learner')),
            ],
        ),
    ]
