# Generated by Django 4.1.4 on 2022-12-31 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="learner_on_roster",
            field=models.ManyToManyField(
                blank=True, related_name="learners", to="accounts.learner"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="learner_on_waitlist",
            field=models.ManyToManyField(
                blank=True, related_name="waitlisted", to="accounts.learner"
            ),
        ),
    ]
