# Generated by Django 4.0.5 on 2022-09-13 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='enrolled_in_course',
            field=models.ManyToManyField(default=1, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='listed_on_waitlist',
            field=models.ManyToManyField(related_name='waitlists', to='lessons.learner'),
        ),
        migrations.AlterField(
            model_name='learner',
            name='associated_with_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
