# Generated by Django 4.0.5 on 2022-09-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_course_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
