# Generated by Django 4.0.5 on 2022-09-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_learner_enrolled_in_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='learner_on_waitlist',
            field=models.ManyToManyField(null=True, related_name='waitlists', to='lessons.waitlist'),
        ),
    ]
