# Generated by Django 4.0.5 on 2022-09-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_learner_learner_on_waitlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learner_on_roster',
            field=models.ManyToManyField(default=1, null=True, related_name='learners', to='lessons.learner'),
        ),
    ]
