# Generated by Django 4.0.5 on 2022-10-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_learner_enrolled_in_course_and_more'),
        ('lessons', '0003_alter_course_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlist',
            name='listed_on_waitlist',
            field=models.ManyToManyField(blank=True, related_name='learners_waitlisted', to='accounts.learner'),
        ),
    ]
