# Generated by Django 4.0.5 on 2022-09-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_course_learner_on_roster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlist',
            name='listed_on_waitlist',
            field=models.ManyToManyField(null=True, related_name='waitlists', to='lessons.learner'),
        ),
    ]
