# Generated by Django 4.1.2 on 2022-10-21 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0005_alter_waitlist_listed_on_waitlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="course_age_range_max",
        ),
        migrations.RemoveField(
            model_name="course",
            name="course_age_range_min",
        ),
        migrations.RemoveField(
            model_name="course",
            name="course_day_of_week",
        ),
        migrations.RemoveField(
            model_name="course",
            name="course_description",
        ),
        migrations.RemoveField(
            model_name="course",
            name="course_end_date",
        ),
        migrations.RemoveField(
            model_name="course",
            name="course_end_time",
        ),
        migrations.RemoveField(
            model_name="course",
            name="course_location",
        ),
        migrations.RemoveField(
            model_name="course",
            name="course_start_date",
        ),
        migrations.RemoveField(
            model_name="course",
            name="course_start_time",
        ),
        migrations.RemoveField(
            model_name="course",
            name="learner_on_roster",
        ),
        migrations.RemoveField(
            model_name="course",
            name="num_spots_available",
        ),
    ]
