# Generated by Django 4.1.2 on 2022-10-21 05:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0006_remove_course_course_age_range_max_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_age_range_max",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="course_age_range_min",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="course_description",
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
