# Generated by Django 4.0.5 on 2022-09-13 01:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0007_alter_learner_learner_on_waitlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='learner_on_roster',
            field=models.ManyToManyField(blank=True, default=1, related_name='learners', to='lessons.learner'),
        ),
        migrations.AlterField(
            model_name='learner',
            name='enrolled_in_course',
            field=models.ManyToManyField(blank=True, default=1, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='learner',
            name='learner_on_waitlist',
            field=models.ManyToManyField(blank=True, default=None, related_name='waitlists', to='lessons.waitlist'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='listed_on_waitlist',
            field=models.ManyToManyField(blank=True, related_name='waitlists', to='lessons.learner'),
        ),
    ]
