# Generated by Django 4.1.2 on 2022-10-21 05:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0007_course_course_age_range_max_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_end_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Enter the date this course will end.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="course_location",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="course_start_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Enter the date this course will begin.",
            ),
            preserve_default=False,
        ),
    ]
