# Generated by Django 4.0.5 on 2022-09-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_alter_course_learner_on_roster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='enrolled_in_course',
            field=models.ManyToManyField(blank=True, default=1, related_name='courses', to='lessons.course'),
        ),
    ]
