# Generated by Django 4.1.2 on 2022-10-21 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0008_course_course_end_date_course_course_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_day_of_week",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="course_end_time",
            field=models.TimeField(
                default=django.utils.timezone.now,
                help_text="Enter the end time for this course (e.g., 02:00 PM)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="course_start_time",
            field=models.TimeField(
                default=django.utils.timezone.now,
                help_text="Enter the start time for this course (e.g., 01:00 PM)",
            ),
            preserve_default=False,
        ),
    ]
