# Generated by Django 4.0.5 on 2022-09-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_alter_learner_enrolled_in_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='enrolled_in_course',
            field=models.ManyToManyField(blank=True, default=None, related_name='courses', to='lessons.course'),
        ),
    ]
