# Generated by Django 4.1.2 on 2022-10-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_learner_enrolled_in_course_and_more"),
        ("lessons", "0009_course_course_day_of_week_course_course_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="learner_on_roster",
            field=models.ManyToManyField(
                blank=True, default=1, related_name="learners", to="accounts.learner"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="num_spots_available",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
