# Generated by Django 4.1.2 on 2022-10-21 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0010_course_learner_on_roster_course_num_spots_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="num_spots_available",
        ),
    ]
