# Generated by Django 4.1.2 on 2022-10-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0012_remove_course_learner_on_roster"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="num_spots_available",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
