# Generated by Django 4.1.2 on 2022-10-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_learner_enrolled_in_course_and_more"),
        ("lessons", "0013_course_num_spots_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="learner_on_roster",
            field=models.ManyToManyField(
                blank=True, related_name="learners", to="accounts.learner"
            ),
        ),
    ]
