# Generated by Django 4.1.2 on 2022-10-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0014_course_learner_on_roster"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="course_day_of_week",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_end_time",
            field=models.TimeField(
                help_text="Enter the end time for this course in Hawaii Standard Time(e.g., 02:00 PM)."
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_start_time",
            field=models.TimeField(
                help_text="Enter the start time for this course in Hawaii Standard Time (e.g., 01:00 PM)."
            ),
        ),
    ]
