# Generated by Django 4.1.3 on 2022-12-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "lessons",
            "0015_course_course_price_alter_course_course_day_of_week_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="waitlist",
            name="course_instructor",
        ),
        migrations.AlterField(
            model_name="course",
            name="course_age_range_max",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_age_range_min",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_day_of_week",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_price",
            field=models.DecimalField(
                decimal_places=2, help_text="Enter price in US dollars.", max_digits=10
            ),
        ),
    ]
