# Generated by Django 4.1.3 on 2022-12-02 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0016_remove_waitlist_course_instructor_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="waitlist",
            old_name="listed_on_waitlist",
            new_name="learner_on_waitlist",
        ),
    ]
