# Generated by Django 4.1.3 on 2022-12-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_learner_enrolled_in_course_and_more"),
        ("lessons", "0017_rename_listed_on_waitlist_waitlist_learner_on_waitlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="learner_on_waitlist",
            field=models.ManyToManyField(
                blank=True, related_name="waitlisted", to="accounts.learner"
            ),
        ),
        migrations.DeleteModel(
            name="Waitlist",
        ),
    ]
